#!/bin/sh

set -e

case "$1" in
  configure)
    :
	#update viz server in DB.
	mysql -u ohmage -p\&\!sickly -e 'update ohmage.preference set p_value = "http://127.0.0.1/R/pub/Mobilize/" where p_key = "visualization_server_address";'
	echo "updated viz server to 127.0.0.1"
	clear
	/usr/lib/ohmage/scripts/showip.sh
    ;;
  abort-upgrade | abort-remove | abort-deconfigure)
    :
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 1;;
esac

#DEBHELPER#

exit 0

