#! /bin/sh

set -e

case "$1" in
  remove | abort-install)
    :
	  #First install of ohmage-viz. Trying to patch preload config
	  cd /usr/lib/ohmage/scripts			
	  patch -RN /etc/opencpu/server.conf preload_config.patch -r /dev/null || true    
    ;;
  purge | disappear | abort-upgrade | upgrade | failed-upgrade)
    :
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 1;;
esac

#DEBHELPER#

exit 0



